:toc:
:toc-placement!:
:toclevels: 3
= Archive Server

A module providing common functionality for HTTP server applications that manage an archive of media files.

toc::[]

== Synopsis
This module implements multiple components that can be used to browse and access media files hosted in an archive:

* An actor that stores the metadata of all songs in the archive and manages different views on them. It groups songs by _media_, which are collections of songs sharing similar properties (based on whatever criteria). Media can be queried for the artists and albums they contain.
* A REST API to query the content of the archive (based on the views of the mentioned actor) and to download media files.
* A base `Controller` implementation to run an HTTP server which exposes the REST API in the xref:src/main/scala/de/oliver_heger/linedj/archive/server/ArchiveController.scala[ArchiveController] class.

These components are agnostic about the archive itself, e.g., where it is hosted or how it is accessed. Concrete applications depending on this module need to deal with these details and initialize the components accordingly. They also have to provide a _resolver_ function to locate and download a specific media file in the managed archive.

[#archive_server_rest_api]
== REST API
The `Route` created by the base `Controller` implementation provides a number of REST endpoints to browse the media files available in the archive. All these endpoints start with the common path `/api/archive` and use the GET method. They return JSON data based on model objects defined in the xref:src/main/scala/de/oliver_heger/linedj/archive/server/model/ArchiveModel.scala[ArchiveModel] object. Table <<tab_endpoints>> lists the most relevant endpoints.

.Endpoints of the Archive Server module
[#tab_endpoints]
[cols="1,3",options="header"]
|====
| Path | Description
| /media
| Returns an object with overview information about all media stored in this archive. Media are the top-level organization structure for media files. Many other endpoints operate on single media. The resulting data lists the names of the media available and their IDs.

| /media/\{id}
| Returns detail information about the medium with the given ID.

| /media/\{id}/artists
| Returns an object with the list of the artists contained on the specified medium. Each artist is listed with the name and the ID.

| /media/\{id}/albums
| Returns an object with the list of albums contained on the specified medium. Each album is listed with its name and ID.

| /media/\{id}/artists/\{artistID}/songs
| Returns an object with the songs of the given artist contained on the specified medium. For songs, different properties are available, provided that they were defined in the metadata of the corresponding media file. This includes the ID, the title, the album, the inception year, the track number on the album, the playback duration and some more.

| /media/\{id}/albums/\{albumID}/songs
| Returns an object with the songs on the given album contained on the specified medium. This is analogous to the songs of an artist, but provides a view based on albums.

| /media/\{id}/artists/\{artistID}/albums
| Returns an object with the albums of a given artist contained on the specified medium. This is analogous to the `/media/\{id}/albums` endpoint, but only selects the albums of the artist with the provided `artistID`.

| /files/\{fileID}/info
| Returns an object with information about the media file with the given ID. This includes the metadata known about this file and also the ID of the medium the file belongs to.

| /files/\{fileID}/download
| This endpoint can be used to download a media file with a specific ID. The result is an octet stream with the content of this file.

The endpoint supports an optional query parameter `stripMedatada`. If it is specified with a value of *true*, the content that is returned does not contain ID3v2 metadata. This can be useful if only the audio information is needed for playback.
|====

[#sec_config]
== Configuration
The `ArchiveController` class manages a configuration file (in XML format) that it loads automatically on application startup. A concrete server application has to provide the default name of this configuration file, and it is looked up in the current user's home directory. This can be overridden on the command line by setting the `configFile` system property to the path of the configuration file to be loaded, such as:

[source, bash]
----
java -DconfigFile=/path/to/my/config.xml -jar archive-server.jar
----

This module evaluates an optional section named `server` in the configuration file. It defines some settings for the HTTP server to launch. The file can then contain further configuration options to be processed by the server application. An example `server` section can look as follows:

[source,xml]
----
<configuration>
    <server>
      <port>8081</port>
      <timeout>30sec</timeout>
    </server>
</configuration>
----

Table <<tab_config_server>> lists the supported configuration options together with their default values.

[#tab_config_server]
.Properties in the server section
[cols="1,3",options="header"]
|====
| Setting | Description

| port
| Defines the port on which the server listens for incoming requests. If not specified, the default port 8080 is used. Note that the server always binds to the interface "0.0.0.0".

| timeout
| Here, a timeout for the interaction with actors during request processing can be specified. The value can be a number with a unit, such as "10s" or "1min". The default timeout is 3 seconds; on slower machines, it may be necessary to increase it.
|====
