/*
 * Copyright 2015-2026 The Developers Team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.oliver_heger.linedj.archive.server.content

import de.oliver_heger.linedj.shared.actors.CachingActor
import de.oliver_heger.linedj.shared.archive.metadata.Checksums
import org.apache.pekko.actor.typed.scaladsl.AskPattern.*
import org.apache.pekko.actor.typed.{ActorRef, Behavior, Scheduler}
import org.apache.pekko.util.Timeout

import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import java.util.Locale
import scala.concurrent.duration.DurationInt
import scala.concurrent.{ExecutionContext, Future}

/**
  * An actor implementation for generating and managing IDs for a specific
  * type of entities contained in a media archive.
  *
  * The IDs of entities like artists and albums are computed dynamically using
  * hash algorithms on the entity names. Since the computation of such hashes
  * produces some load, the task is delegated to actors, so that it can be
  * performed in parallel. This actor implementation manages a central cache of
  * identifiers. When queried for the ID of a specific entity, it first checks
  * its cache. If the ID has not yet been computed, the computation is
  * triggered now asynchronously.
  *
  * As metadata for songs in the archive may be incomplete, there are special
  * synthetic entities for an undefined artist or undefined album. Those
  * entities do not have a name, but they still need an ID, so that they can be
  * accessed via the REST API. This actor produces a special ID for such
  * entities to avoid conflicts with autogenerated IDs.
  *
  * When generating IDs for names, this actor first performs a conversion to
  * lowercase on entity names. So, names differing only in case are assigned
  * the same IDs.
  */
object IdManagerActor:
  /**
    * Alias of a function that is used to calculate IDs for entities based on
    * their names. The function expects the entity name as input and returns
    * its ID.
    */
  type IdCalculatorFunc = String => String

  /**
    * Alias for a type used to represent the name of an entity for which an ID
    * can be generated. The name is not always present, for instance, in case
    * of a song for which no artist or album is known.
    */
  type EntityName = Option[String]

  /**
    * A type alias for the command type supported by the actor returned by the
    * factory.
    */
  type QueryIdCommand = CachingActor.CacheCommand[EntityName, String]

  /**
    * A data class to represent the response of a [[QueryIdCommand.GetIds]]
    * command. Here, the response consists of a map that associates all passed
    * in names with their IDs.
    *
    * @param ids the mapping of the computed IDs
    */
  final case class GetIdsResponse(ids: Map[EntityName, String])

  /** The algorithm used by the default hash-based ID calculator function. */
  private val HashAlgorithm = "SHA-1"

  /** An ID value that is returned for an undefined name. */
  private val UndefinedID = "0"

  /**
    * A default [[IdCalculatorFunc]] that uses a standard hash algorithm to
    * calculate an ID value.
    */
  val HashIdCalculatorFunc: IdCalculatorFunc = input =>
    val digest = MessageDigest.getInstance(HashAlgorithm)
    Checksums.toHexString(digest.digest(input.getBytes(StandardCharsets.ISO_8859_1)))

  /**
    * A factory trait supporting the creation of new actor instances.
    */
  trait Factory:
    /**
      * Returns the [[Behavior]] for a new actor instance. The way how this
      * instance generates IDs can be configured via the parameters.
      *
      * @param idPrefix a prefix that is prepended to all IDs generated by the
      *                 new actor instance; this can be used to have disjunct
      *                 IDs for different types of entities
      * @param idFunc   the function to compute ID values
      * @param ec       the execution context
      * @return the [[Behavior]] of the new actor instance
      */
    def apply(idPrefix: String, idFunc: IdCalculatorFunc = HashIdCalculatorFunc)
             (using ec: ExecutionContext): Behavior[QueryIdCommand]

  /**
    * A default [[Factory]] for creating new actor instances.
    */
  val newInstance: Factory = new Factory:
    override def apply(idPrefix: String, idFunc: IdCalculatorFunc)
                      (using ec: ExecutionContext): Behavior[QueryIdCommand] =
      CachingActor.newInstance(hashCalculatorResolverFunc(idPrefix, idFunc))

  /**
    * A [[Timeout]] in implicit scope for the ''ask'' operations used by this
    * implementation. Here a rather long value is set. Real timeouts are
    * handled by the content management actor.
    */
  private given requestTimeout: Timeout(1.hour)

  extension (a: ActorRef[QueryIdCommand])
    /**
      * A convenience function to query the IDs for multiple names from an ID
      * manager actor. This function performs an ''ask'' operation on this
      * actor and wraps the required command creation and timeout handling.
      *
      * @param names     a collection of names to request IDs for
      * @param scheduler the scheduler for the ask operation
      * @param ec        the execution context
      * @return a [[Future]] with the response message
      */
    def getIds(names: Iterable[EntityName])
              (using scheduler: Scheduler, ec: ExecutionContext): Future[GetIdsResponse] =
      a.ask[CachingActor.MultiCacheResponse[EntityName, String]]: ref =>
        CachingActor.CacheCommand.GetMultiple(names, ref)
      .map: cacheResponse =>
        GetIdsResponse(cacheResponse.resolved)

  /**
    * Returns a function to resolve unknown keys. This implementation applies
    * the given [[IdCalculatorFunc]] on the key and handles all corner cases.
    *
    * @param idPrefix the prefix for all identifiers
    * @param idFunc   the function to compute ID values
    * @param ec       the execution context
    * @return the function to resolve unknown cache keys
    */
  private def hashCalculatorResolverFunc(idPrefix: String, idFunc: IdCalculatorFunc)
                                        (using ec: ExecutionContext):
  CachingActor.KeyResolverFunc[EntityName, String] =
    case Some(key) =>
      Future:
        s"${idPrefix}_${idFunc(key.toLowerCase(Locale.ROOT))}"
    case None =>
      Future.successful(idPrefix + UndefinedID)
