/*
 * Copyright 2015-2025 The Developers Team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.oliver_heger.linedj.archive.server.content

import de.oliver_heger.linedj.shared.archive.metadata.Checksums
import org.apache.pekko.actor.typed.scaladsl.{ActorContext, Behaviors}
import org.apache.pekko.actor.typed.{ActorRef, Behavior}

import java.nio.charset.StandardCharsets
import java.security.MessageDigest
import java.util.Locale
import scala.concurrent.Future

/**
  * An actor implementation for generating and managing IDs for a specific
  * type of entities contained in a media archive.
  *
  * The IDs of entities like artists and albums are computed dynamically using
  * hash algorithms on the entity names. Since the computation of such hashes
  * produces some load, the task is delegated to actors, so that it can be
  * performed in parallel. This actor implementation manages a central cache of
  * identifiers. When queried for the ID of a specific entity, it first checks
  * its cache. If the ID has not yet been computed, the computation is
  * triggered now asynchronously.
  *
  * As metadata for songs in the archive may be incomplete, there are special
  * synthetic entities for an undefined artist or undefined album. Those
  * entities do not have a name, but they still need an ID, so that they can be
  * accessed via the REST API. This actor produces a special ID for such
  * entities to avoid conflicts with autogenerated IDs.
  *
  * When generating IDs for names, this actor first performs a conversion to
  * lowercase on entity names. So, names differing only in case are assigned
  * the same IDs.
  */
object IdManagerActor:
  /**
    * Alias of a function that is used to calculate IDs for entities based on
    * their names. The function expects the entity name as input and returns
    * its ID.
    */
  type IdCalculatorFunc = String => String

  /**
    * Alias for a type used to represent the name of an entity for which an ID
    * can be generated. The name is not always present, for instance, in case
    * of a song for which no artist or album is known.
    */
  type EntityName = Option[String]

  /** The algorithm used by the default hash-based ID calculator function. */
  private val HashAlgorithm = "SHA-1"

  /** An ID value that is returned for an undefined name. */
  private val UndefinedID = "0"

  /**
    * An enumeration defining the commands available to query ID values for
    * entities in the archive.
    */
  enum QueryIdCommand:
    /**
      * A command to query the ID for a single entity.
      *
      * @param name    the entity name for which an ID is requested
      * @param replyTo the actor expecting the response message
      */
    case GetId(name: EntityName,
               replyTo: ActorRef[GetIdResponse])
  end QueryIdCommand

  /**
    * A data class to represent the response of a [[QueryIdCommand.GetId]]
    * message. An instance holds the entity name and the associated ID.
    *
    * @param name the name of the affected entity
    * @param id   the ID for this entity name
    */
  final case class GetIdResponse(name: EntityName,
                                 id: String)

  /**
    * An internal data type to represent the possible states of an entry in the
    * ID value cache. When an ID is requested which is not yet known, the actor
    * adds an [[IdCacheState.IdPending]] object to the cache to indicate that
    * the computation of this ID is currently in progress. This allows handling
    * incoming requests for the same key while the computation is still
    * running. When the result is available the entry in the cache is replaced
    * by an [[IdCacheState.IdAvailable]] instance, and all clients in the
    * pending instance receive a notification.
    */
  private enum IdCacheState:
    /**
      * State indicating that the ID value for this element is available.
      *
      * @param id the ID value
      */
    case IdAvailable(id: String)

    /**
      * State indicating that the ID computation is still in progress. The
      * state stores information about the waiting clients, so that they can be
      * notified when the ID becomes available.
      *
      * @param requests the pending requests
      */
    case IdPending(requests: List[QueryIdCommand.GetId])
  end IdCacheState

  /**
    * An internally used message class this actor sends to itself when the
    * computation of an ID value is finished.
    *
    * @param key   the key of the affected entity
    * @param value the calculated ID value
    */
  private case class IdCalculated(key: String, value: String)

  /**
    * Type alias for the union type of the commands processed by this actor.
    */
  private type IdManagerCommand = QueryIdCommand | IdCalculated

  /**
    * A default [[IdCalculatorFunc]] that uses a standard hash algorithm to
    * calculate an ID value.
    */
  val HashIdCalculatorFunc: IdCalculatorFunc = input =>
    val digest = MessageDigest.getInstance(HashAlgorithm)
    Checksums.toHexString(digest.digest(input.getBytes(StandardCharsets.ISO_8859_1)))

  /**
    * A factory trait supporting the creation of new actor instances.
    */
  trait Factory:
    /**
      * Returns the [[Behavior]] for a new actor instance. The way how this
      * instance generates IDs can be configured via the parameters.
      *
      * @param idPrefix a prefix that is prepended to all IDs generated by the
      *                 new actor instance; this can be used to have disjunct
      *                 IDs for different types of entities
      * @param idFunc   the function to compute ID values
      * @return the [[Behavior]] of the new actor instance
      */
    def apply(idPrefix: String, idFunc: IdCalculatorFunc = HashIdCalculatorFunc): Behavior[QueryIdCommand]

  /**
    * A default [[Factory]] for creating new actor instances.
    */
  val newInstance: Factory = (idPrefix, idFunc) =>
    handleCommand(idPrefix, idFunc, Map.empty).narrow

  /**
    * The main command handler function of the ID manager actor.
    *
    * @param idPrefix the prefix for IDs
    * @param idFunc   the function to compute IDs
    * @param ids      the cache for already computed ID values
    * @return the next behavior of this actor
    */
  private def handleCommand(idPrefix: String,
                            idFunc: IdCalculatorFunc,
                            ids: Map[String, IdCacheState]): Behavior[IdManagerCommand] =
    Behaviors.receive:
      case (context, request@QueryIdCommand.GetId(name, replyTo)) =>
        val (nextIds, optResponse) = name match
          case None =>
            (ids, Some(GetIdResponse(None, idPrefix + UndefinedID)))
          case Some(value) =>
            getOrCalculateId(context, request, value, idPrefix, idFunc, ids)
        optResponse.foreach(replyTo.!)
        if nextIds ne ids then
          handleCommand(idPrefix, idFunc, nextIds)
        else
          Behaviors.same

      case (context, IdCalculated(key, value)) =>
        ids(key) match
          case IdCacheState.IdPending(requests) =>
            context.log.info("ID calculated for key '{}'. Notifying {} client(s).", key, requests.size)
            requests.foreach: request =>
              request.replyTo ! GetIdResponse(request.name, value)
            val nextIds = ids + (key -> IdCacheState.IdAvailable(value))
            handleCommand(idPrefix, idFunc, nextIds)
          case _ => // Should actually not happen
            Behaviors.same

  /**
    * Obtains the ID for the given name either from the cache or by computing
    * it and updating the cache. Return a tuple with the updated cache and an
    * optional response to be sent to the requesting actor.
    *
    * @param context  the context of this actor
    * @param request  the request for an ID to be processed
    * @param name     the name of the entity for which an ID is requested
    * @param idPrefix the prefix for IDs
    * @param idFunc   the function to compute IDs
    * @param ids      the cache for already computed ID values
    * @return the updated cache and a response to send
    */
  private def getOrCalculateId(context: ActorContext[IdManagerCommand],
                               request: QueryIdCommand.GetId,
                               name: String,
                               idPrefix: String,
                               idFunc: IdCalculatorFunc,
                               ids: Map[String, IdCacheState]): (Map[String, IdCacheState], Option[GetIdResponse]) =
    val key = name.toLowerCase(Locale.ROOT)
    ids.get(key) match
      case Some(IdCacheState.IdAvailable(id)) =>
        (ids, Some(GetIdResponse(Some(name), id)))
      case Some(IdCacheState.IdPending(requests)) =>
        val nextPending = IdCacheState.IdPending(request :: requests)
        (ids + (key -> nextPending), None)
      case None =>
        context.log.info("Calculating ID for '{}'.", key)
        import context.executionContext
        Future:
          s"${idPrefix}_${idFunc(key)}"
        .foreach: id =>
          context.self ! IdCalculated(key, id)
        val pending = IdCacheState.IdPending(List(request))
        (ids + (key -> pending), None)
