= Logging configuration

This folder contains the content of two fragment OSGi bundles that are required
to configure and use https://logging.apache.org/log4j/2.x/[Apache Log4j] in an
OSGi environment.

In an OSGi container, the logging framework does not work out of the box, as
the API bundle cannot detect the logging implementation, and the configuration
file cannot be found. Following the approach described in
https://craftsmen.nl/getting-log4j2-to-work-in-an-osgi-context/[this article],
two fragment bundles are created that are added to the Log4J API and Core
bundles and provide the necessary information. The article is a bit out-dated
though; the logging implementation is now discovered from the API bundle via
Java's service loader mechanism; therefore, the API fragment bundle needs to
expose the corresponding service definitions.

Via the configuration provided by these bundles, Log4j2 can capture the logging
output generated by the Pekko modules (that are using
https://www.slf4j.org/[Slf4j]) and LineDJ itself. The
https://github.com/oheger/jguiraffe[JGUIraffe] library used for the UI in
contrast makes use of
https://commons.apache.org/proper/commons-logging/[Apache Commons Logging].
Unfortunately, this framework cannot be handled analogously to Slf4j due to its
reliance on the Thread Context Class Loader being set; some logic is needed to
fix this. Since all UI-related bundles depend on the
link:../audioPlatform/README.md[Platform] module, the configuration specific to
Commons Logging is included there.
