= LineDJ Platform

A project offering basic functionality for applications running on the LineDJ
platform.

== Functionality

The main purpose of this project is to implement basic services and
infrastructure that can be used by applications. By providing a base class for
applications, it also kind of defines a programming model for such
applications. Applications are based on the
https://github.com/oheger/jguiraffe[JGUIraffe] library; this library allows the
creation of UI applications using concepts like XML-based UI definitions,
action and command objects, and dependency injection.

The classes and interfaces contained in the _Platform_ project can roughly be
divided into two parts:

* Providing basic functionality for the platform.
* Defining a framework for client applications running on the platform.

== Platform services

The platform offers a number of fundamental services available to all client
applications. The services are managed and started by the
`ClientManagementApplication` class. This is a non-visual _JGUIraffe_
application; it is the first application which starts on the platform. It then
performs the necessary initialization and creates an object of type
`ClientApplicationContext` serving as main entry point into platform
functionality. This object is registered as on OSGi services. Then client
applications depending on this service can start.

Via the client application context the following central services are
available:

=== Actor system

The platform manages an actor system which can be used by client applications
to run non-blocking background tasks. Actually, all actions not directly
related to UI updates should be run in the background, and the actor system is
a good way to achieve this.

The actor system can also be used for interactions with the media archive, for
instance to request media files from the archive. In order to create new actors
and deploy them on the actor system, the `ClientApplicationContext` offers an
_actor factory_.

=== Message bus

The message bus is a generic means for UI applications running on the platform
to communicate with each other. It offers a simple publish-subscribe model. One
speciality is that the bus is especially intended for UI-related communication;
therefore, all messages published via it are delivered in the UI thread.

The message bus is also used to deliver the responses of requests to the media
archive. An application can for instance query a list of media currently
available in the archive. The request is processed by actors communicating with
the archive (which may involve remote calls, depending on the way the archive
is connected). The response is then published on the message bus from where it
can be received by registered listeners.

Client applications typically register specialized listeners on the message bus
when they start up. The listeners are then notified about certain events or
when specific data becomes available. They can then react accordingly, e.g.
update the UI.

=== Media facade

This object allows communication with the media archive. The interface is
rather low-level: The functionality provided by the archive is implemented by a
couple of actors. Via the facade messages can be sent to these actors. (As has
already been mentioned, the responses then typically arrive on the message
bus.) As this may not always be the most convenient form of interaction, there
are some extension mechanisms in place managing dedicated data. Those are
described later on.

=== Client for the media archive
If configured, this module starts a discovery operation to locate an HTTP server with media files in the local network. When this operation yields a success result, the module registers a service instance of type xref:src/main/scala/de/oliver_heger/linedj/platform/archiveclient/ArchiveService.scala[ArchiveService] that allows interaction with the media archive. Applications can declare a dependency to this service and by that gain access to the media archive.

=== Central configuration

The client application context offers a way to query or store central
configuration. In addition, each client application can have its own specific
configuration. Access to configuration data is provided by the
http://commons.apache.org/proper/commons-configuration/[Apache Commons Configuration]
library.

There can also be an optional central configuration file for the platform as a whole. This is read and made available by the xref:../platformStartup/README.adoc[Platform Startup] module. The `ClientApplicationContext` exposes the platform configuration as a property. If no platform configuration is defined, this property holds an empty configuration.

=== Application management

On a LineDJ platform an arbitrary number of collaborating applications can run.
A component named _application manager_ is responsible for keeping track on
these applications. It allows querying the list of currently available
applications, sends notifications when there are changes, and manages the
shutdown of the platform.

Shutdown handling is not trivial if there are multiple active applications.
For instance, what does it mean if a user closes the window of an application?
Should only this application be closed or should the whole platform go down?
The answer probably depends on a concrete deployment of a LineDJ platform.

To handle different use cases, there are multiple implementations of the
application manager service available. When creating a deployment a suitable
implementation can be chosen. The following implementations are available:

* link:../appShutdownOneForAll[OneForAllShutdownAppManager]
* link:../appWindowHiding[WindowHidingApplicationManager]

=== Shutdown management

While <<Application management>> involves the shutdown of applications, every
OSGi component running on the platform may need to do special actions when the
system is going down; for instance, some data may have to be persisted, so that
it is available on the next execution. Such shutdown actions are not trivial to
handle correctly in a dynamic environment; there are multiple problems:

* The components a specific component depends on and which it requires for
  executing its shutdown actions may already been shutting down.
* Disabling of an OSGi component via the default `deactivate()` method is
  triggered from the OSGi management thread. This makes it complicated to
  access data managed by other threads (especially the UI thread) and do
  asynchronous stuff.

To support a graceful shutdown and simplify the logic involved, the platform
therefore offers an extended shutdown management implemented (mostly) by the
link:./src/main/scala/de/oliver_heger/linedj/platform/app/ShutdownHandler.scala[ShutdownHandler]
class. Here is a short summary how it works:

* Components wanting to take part in the shutdown management, have to register
  themselves as _shutdown observers_ at the shutdown handler. For this purpose,
  they need to send a message of type `RegisterShutdownObserver` on the system
  message bus. The message contains the component's unique ID and a reference
  to a `ShutdownObserver` implementation.
* The `ShutdownObserver` trait defines a single method `triggerShutdown()`.
  When the platform is going down, the shutdown handler invokes this method for
  each registered component on the UI thread. During the invocation, it passes
  an object of type `ShutdownCompletionNotifier`.
* The components invoked can now execute their specific shutdown logic,
  synchronously or asynchronously as fits best for them. When they are done
  they must call back the `ShutdownCompletionNotifier` they have been passed.
* The shutdown handler monitors the components involved and waits until all
  their completion notifications have arrived (or a configurable timeout
  occurs). Then the shutdown actually takes place.

== Client applications

LineDJ compatible applications extend the
link:src/main/scala/de/oliver_heger/linedj/platform/app/ClientApplication.scala[ClientApplication]
base class, which in turn is a _JGUIraffe_ application class. Client application
classes themselves are typically very simple because the whole functionality for
correctly startup the application and register required OSGi services is
provided by the base class. The application's UI is described in an XML-based
script.

The client application base class offers the following functionality available
for all client applications:

=== Life-cycle management

The class makes sure that an application is properly started and connected to
the services of the LineDJ platform. Also, proper shutdown handling is
implemented, for instance by taking care that the application's configuration
is automatically saved or that an application can veto against its shutdown.
This is achieved by interacting with the
<<Application management,application manager>> installed on the platform.

The application object itself is registered as an OSGi service. This is a
prerequisite for it to take part in the life-cycle management of the whole
platform.

=== Providing access to central beans

Each client application has access to the central `ClientApplicationContext`
object; it is stored as a property in the application base class. During
startup, the service objects described in the previous section are also added
to the application's bean context (the central configuration for dependency
injection), so that they are available for UI scripts and can be passed to
controller or event listener classes.

=== Configuration management

Each client application can have its own configuration in which it can store
persistent data. The base name of the configuration must be provided as a
constructor argument to the super class; this class then ensures that a
corresponding configuration file is created in the user's home directory.
Further information about naming conventions and how they can be adapted using
system properties can be found at the
link:src/main/scala/de/oliver_heger/linedj/platform/app/ApplicationStartup.scala[ApplicationStartup]
trait.

== Media Interface Extensions

Direct interactions with the media archive can be inconvenient due to the
low-level nature of the interface. In addition, it can be problematic if
multiple applications running on the platform send requests in parallel to the
archive and receive responses on the shared message bus. How can it be
determined which response is for which client? Another point is that multiple
client applications may request the same data from the media archive; should
data be fetched again (maybe via remote calls) that has already been retrieved
by the client platform?

To solve these problems, so-called _media interface extensions_ have been
introduced. The idea is that an extension manages specific data in a way global
for a client platform (i.e. the OSGi container hosting the platform and all
currently deployed client applications). Applications do not interact with the
media archive directly, but send a request to the corresponding extension which
also contains a callback for being notified when results become available or
state changes occur. This is referred to as a _consumer_ relation.

The extension is responsible for managing the data it controls: It will
typically send a request to the media archive when the first consumer request
is received. When the answer to the request arrives it is distributed to all
consumers currently registered. The extension is also free to cache the
response, so that new consumers requesting this data can be served instantly.

Extensions also keep track about the status of the archive: If it becomes
unavailable and available again later, or if a new scan for media data is
started, the data under its control is considered stale, and a new request is
sent (if still consumers are registered).

In the following the extensions available are shortly described. The source
code for extensions can be found in the
link:src/main/scala/de/oliver_heger/linedj/platform/mediaifc/ext[mediaifc.ext
package].

=== Media Archive Available extension
 
As the media archive can run on a remote machine, the connection can drop at
any time. This extension permanently monitors the current state of the archive
availability. Registered consumers receive an _archive available_ or _archive
unavailable_ notification as soon as a change in state is detected.
 
This is useful for applications that interact with the media archive. When the
archive is currently not available this can be reflected in the UI of the
application; for instance, menu items could be disabled.
 
=== Media Archive State Listener extension
 
With this extension update notifications about the state of the media archive
can be received. The state of the archive contains statistics information
about the data currently stored in the archive (such as the number of media or
songs, the total playback duration, etc.).
 
It is also possible that a scan for media is triggered. Then the archive
re-inspects the folder structure with media files and updates itself. This may
lead to changes in the list of media available.
 
Applications that rely on this information - for instance a media browser
application - can use this extension to keep track on changes in the amount of
data managed by the archive.
 
=== Available Media extension
 
_Available media_ is a data structure listing IDs and some metadata about all
media currently managed by the media archive. This is probably of interest for
many applications running on the platform allowing the user to do something
(browse, search, playback, ...) with media files. When a scan for media files
runs and changes are detected this information is updated automatically and
published to registered consumers. So this extension could be an alternative
to the _Media Archive State Listener_ extension for applications only
interested in media information.
 
=== Metadata Cache extension
 
It is a frequent use case to display information about media and the songs
they contain. From the media archive the content of a medium can be queried
(there is even support for a listener registration if currently a scan is in
progress and the information about the medium is updated). Querying a medium
every time it is accessed by the user from the archive may be a waste of
bandwidth, especially if the user only works on a subset of media. Therefore,
this extension offers caching functionality on media.
 
To use this extension, media information is not directly requested from the
archive, but by sending a corresponding message on the message bus. The
message is received by the cache extension, and it checks whether data for
this medium is already contained in the cache. If so, an answer can be sent
directly to the consumer; otherwise, a request to the media archive is
created, and the consumer is given a response when this request is processed.
 
The cache can be configured with a maximum number of entries. When this limit
is reached media that have not been accessed recently are removed from the
cache (the cache has LRU semantics).
 
== Configuration
The _Platform_ module obtains its configuration from the central platform configuration provided by the xref:../platformStartup/README.adoc[Platform Startup] module. The startup module evaluates a system property named `LineDJ_PlatformConfigFile` that can contain the name or path of the platform configuration file. If it is defined, the module reads the configuration file and makes it available to other modules.

The platform configuration file is expected to be an XML file containing a section named `platform` which is evaluated by components in this module. The following fragment shows an example with the relevant configuration properties:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<configuration>
    <platform>
        <shutdownTimeout>10000</shutdownTimeout>
        <media>
            <cacheSize>3000</cacheSize>
        </media>
        <mediaArchive>
            <discovery>
                <multicastAddress>231.1.2.3</multicastAddress>
                <port>10101</port>
                <requestCode>Hello!</requestCode>
                <timeout>58s</timeout>
                <minBackoff>19sec</minBackoff>
                <maxBackoff>5min</maxBackoff>
            </discovery>
            <requestTimeout>38s</requestTimeout>
        </mediaArchive>
    </platform>
</configuration>
----

Table <<tab_platform_config>> lists the configuration options supported by the _Platform_ module:

[#tab_platform_config]
.Configuration settings of the Platform module
[cols="1,3,1",options="header"]
|====
| Setting | Description | Default

| media / cacheSize
| The number of entries that can be stored in the _Metadata Cache_ extension. When this limit is reached older media are removed from the cache.
| 2500
| shutdownTimeout
| Defines a timeout (in milliseconds) for the shutdown handler to wait for the shutdown completed notifications of registered shutdown observers. (Refer to <<Shutdown management>>.) After this time is over, the shutdown takes place, no matter whether there are still outstanding notifications.
| 5000

| mediaArchive / discovery / multicastAddress
| Specifies the multicast address for the discovery operation for the archive server. The discovery component sends a UDP request to this address. This is a mandatory property; if it is unspecified, no discovery operation is performed.
| None

| mediaArchive / discovery / port
| Specifies the port for the discovery operation for the archive server. This is the port the archive server is listening on for incoming discovery requests. This is a mandatory property; if it is unspecified, no discovery operation is performed.
| None

| mediaArchive / discovery / requestCode
| Specifies the request code to send to the archive server during the discovery operation. The server typically only reacts on the correct code. This is a mandatory property; if it is unspecified, no discovery operation is performed.
| None

| mediaArchive / discovery / timeout
| The timeout when waiting for the response of a discovery request. If no response is received within this timeout, the discovery component considers the current discovery operation a failure and retries it later. The value is expected to be in seconds per default, but can have an optional unit identifier.
| 10 sec

| mediaArchive / discovery / minBackoff
| Defines the minimum delay before retrying a failed discovery request. The value is expected to be in seconds per default, but can have an optional unit identifier.
| 5 sec

| mediaArchive / discovery / maxBackoff
| Defines the maximum delay for retrying a failed discovery request. When discovery requests are not answered the discovery component doubles the delay between requests every time. With this property, users can specify a maximum delay. The value is expected to be in seconds per default, but can have an optional unit identifier.
| 2 min

| mediaArchive / requestTimeout
| This property determines the timeout when sending requests to the media archive server. The archive client service considers requests that are not answered in this time as failed.
| 30 sec
|====
