#
# Copyright 2015-2026 The Developers Team.
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# English resources for the LineDJ Archive Browser application.

# Resources used by the main window
main_title = LineDJ Archive Browser

menu_file_text = File
menu_file_mnemo = F

media_lab_media = Available media:

tcol_song_artist = Artist
tcol_song_title = Title
tcol_song_track = Track No
tcol_song_duration = duration

stat_medium_loading = Loading data for medium {0}
stat_album_loading = Loading songs of album {0}
stat_artist_loading = Loading songs of artist {0}
stat_loading_error = Error: {0}
