:toc:
:toc-placement!:
:toclevels: 3
= Player Server

A module implementing a server on top of the player engine modules.

toc::[]

== Synopsis
This module provides an alternative player implementation. Instead of a desktop OSGi application, the player is made
available via an HTTP server that allows controlling playback via REST calls. The intended use case is that the server
runs on a machine in the local network, maybe on a https://www.raspberrypi.com/[Raspberry Pi]. The exposed player can then be controlled from other
devices in the network - either via the REST API or the <<player_ui>>. If a mobile device is used for this purpose, this works similar to a remote control.

Currently, only the radio player is exposed via the server implementation. This may change in the future to also
support the audio player.

== Network discovery
Since the player server can run on an arbitrary machine on the local network, it may not always have the same IP
address. This makes it difficult for clients to interact with the server. To solve this problem, there is support for a
discovery mechanism.

The discovery mechanism is based on https://www.baeldung.com/java-broadcast-multicast[multicast UDP addresses]: The
server application launches a listener on a configurable multicast group and port. When this listener receives a
request with a specific payload it sends an answer back that contains the base URL of the server. So, clients can send
a corresponding multicast request. From the response, they can obtain the URL for further interactions with the server.

The discovery mechanism implemented by the server is compatible with the https://github.com/oheger/WifiControl[Wi-Fi Control] app. So, this Android app can be used to control the player via its UI. More details about the protocol used for discovery can be found in the https://github.com/oheger/WifiControl/blob/main/docs/Discovery.adoc[protocol specification].

[#player_ui]
== UI
The player server defines a REST API that can be used to query the available radio sources, switch to a specific radio source, and start or stop playback. Via this API, programmatic access is possible.

As an alternative, a UI is available which is served via a <<player_configuration,configurable>> endpoint. This transforms the player server into an interactive Web application. The UI is not part of this repository, since it is based on a different implementation technology. It is located in the https://github.com/oheger/player-server-ui[Player Server UI] repository.

[#player_configuration]
== Configuration
The server is configured via a configuration file that is read via the
https://commons.apache.org/proper/commons-configuration/userguide_v1.10/howto_configurationbuilder.html#Using_DefaultConfigurationBuilder[DefaultConfigurationBuilder]
class from https://commons.apache.org/proper/commons-configuration/index.html[Apache Commons Configuration] 1.x.
The file can reference the following options:

* The configuration of the link:../radioPlayer/README.adoc[radio player]. This includes the definition of the radio
  sources available.
* A configuration named _currentConfig_ that is used to store current values like the currently selected radio source.
* A configuration specific to the server. This is explained in detail below.

The following listing shows an example configuration file:

.Example configuration definition file
[source,xml]
----
<configuration>
    <xml config-name="radioSourcesConfig" fileName=".lineDJ-radio-sources.xml" config-at="player"/>
    <xml config-name="serverConfig" fileName="server.xml" />
    <xml config-name="currentConfig" fileName=".lineDJ-radioplayer.xml"/>
</configuration>
----

In this example, the configuration named _radioSourcesConfig_ contains the data about radio sources, including
time- or metadata-based exclusions. The referenced file `.lineDJ-radio-sources.xml` is processed via the
link:../radioPlayerEngineConfig/README.adoc[Radio player engine config] module; hence, it must be compliant to the
format expected by this module.

The next configuration populated from the `server.xml` file defines the server itself and the radio player engine. An
example is provided later in this section.

The configuration named _currentConfig_ can be initially empty. It is used by the server to record some settings, so
that they survive a restart.

The server configuration defines fundamental properties of the server application and the audio and radio player
engines. An example file could look as follows:

.Example server configuration
[source,xml]
----
<configuration>
    <serverPort>8080</serverPort>
    <lookupMulticastAddress>231.10.1.2</lookupMulticastAddress>
    <lookupPort>5511</lookupPort>
    <lookupCommand>whereAreYou?</lookupCommand>
    <uiContentFolder>content/player-server-ui/dist</uiContentFolder>
    <uiPath>/welcome.html</uiPath>
    <player>
        <memoryBufferSize>65536</memoryBufferSize>
        <playbackContextLimit>8192</playbackContextLimit>
        <blockingDispatcherName>io-dispatcher</blockingDispatcherName>
    </player>
</configuration>
----

The configuration for the audio and the radio player engines has already been discussed at the corresponding player
applications. Table <<tab-server-properties>> describes the configuration properties that are specific for the player
server application.

[#tab-server-properties]
.Server configuration
[cols="1,3,1",options="header"]
|====
|Property|Description|Default

|serverPort
|The port on which the HTTP server should listen.
|8080

|lookupMulticastAddress
|The multicast UPD address on which the server can be queried for its UI endpoint.
|231.10.0.0

|lookupPort
|Defines the lookup port. A query for the UI endpoint of this server has to be sent to the lookup multicast address
 and this port.
|4321

|lookupCommand
|Specifies the lookup command. A lookup query must have this string as payload; otherwise, it is ignored.
|playerServer?

|uiContentFolder
|This property defines the local folder which contains the assets of the UI. This folder is served as a static
 resource. This can be either an absolute or a relative path. The referenced folder must contain the artifacts that comprise the player server UI; this is typically the output of the build process of the https://github.com/oheger/player-server-ui[Player Server UI] project.
|ui

|uiPath
|A property to define the URL path for loading the web UI. When requesting this path from the HTTP server, the player
 UI (as defined by the `uiContentFolder` property) is returned. Other endpoints, especially the REST API endpoints, are static.
|/ui/index.html

|shutdownCommand
|Here an arbitrary command can be specified that the server will execute (in a new process of the operating system) during its shutdown phase. The intention behind this is to do some cleanup or trigger final actions when the server terminates. For instance, if the server is running on a Raspberry Pi that is used exclusively as an Internet radio, it may make sense to shut down the machine on termination of the server; so, here the corresponding shutdown command could be provided.
|(undefined)
|====

== Native image
It is possible to build a https://www.graalvm.org/latest/reference-manual/native-image/[GraalVM native image] for the Player Server application. This could have some benefits like reduced startup times or memory consumption. The native image is constructed using the https://www.scala-sbt.org/sbt-native-packager/[SBT Native Packager] plugin.

Building the native image requires a local GraalVM installation with the `native-builder` tool available on the path. This is the standard configuration for the SBT Native Packager plugin, which just invokes the `native-builder` command.

WARNING: A fully functional native image could be built successfully using the GraalVM Community Edition in version 24.0.1. With the GraalVM 21.0.2 version, the image could be built without failures, but audio playback was not possible. This seems to be a bug in older GraalVM versions.

With a local GraalVM installation that meets the described prerequisites available, the following SBT command generates the native image:

 sbt playerServer/GraalVMNativeImage/packageBin

The resulting artifacts can be found in the folder `playerServer/target/graalvm-native-image`. They consist of the actual binary for the Player Server application plus the `libjsound.so` library required for audio playback using the JavaX Sound API. This library needs to be placed in the same folder as the binary when launching the application.

This repository also contains a https://github.com/oheger/LineDJ/actions/workflows/player-server-native-image.yml[workflow] that generates native images for the Player Server application for different operation systems and target architectures.
