/*
 * Copyright 2015-2025 The Developers Team.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.oliver_heger.linedj.player.shell

import org.apache.logging.log4j.Level
import org.apache.logging.log4j.core.appender.AbstractAppender
import org.apache.logging.log4j.core.config.Configurator
import org.apache.logging.log4j.core.config.builder.api.ConfigurationBuilderFactory
import org.apache.logging.log4j.core.layout.PatternLayout
import org.apache.logging.log4j.core.{Appender, Layout, LogEvent, LoggerContext, StringLayout}
import org.apache.pekko.actor as classic
import org.apache.pekko.actor.typed.scaladsl.Behaviors
import org.apache.pekko.actor.typed.scaladsl.adapter.*
import org.apache.pekko.actor.typed.{ActorRef, Behavior}
import org.jline.reader.PrintAboveWriter

import java.nio.charset.StandardCharsets
import java.util.concurrent.atomic.AtomicReference

/**
  * An object providing functionality for outputting text in the shell.
  *
  * Text output in the command execution loop is sometimes tricky. It should
  * not interfere with the input of commands. Also, some commands produce
  * asynchronous output which needs to be handled correctly. A third source of
  * text that can come in at any point of time is log output generated by the
  * player engine.
  *
  * The task of this module is to handle the different kinds of text to be
  * displayed correctly and make sure that they do not disturb each other. This
  * is achieved by providing an actor that eventually handles all text output.
  * This actor is invoked by the main command loop to print the output
  * generated by commands. To capture the log output, this module contains a
  * custom [[Appender]] implementation that delegates log events to the actor
  * as well.
  */
object Output:
  /** The internal name used by the custom appender. */
  private val AppenderName = "OutputActorAppender"

  /**
    * An enumeration class defining the commands supported by the output actor.
    */
  private enum OutputCommand:
    /**
      * Command to output a (already formatted) log message.
      *
      * @param message the message to output
      */
    case OutputLog(message: String)

    /**
      * Command to output text (generated by commands).
      *
      * @param lines the lines of text to output
      */
    case OutputText(lines: List[String])

    /**
      * Command to stop the output actor. This should be sent as a final
      * cleanup step.
      */
    case Stop
  end OutputCommand

  /**
    * Stores the reference to the central output actor. This actor is not
    * available when this module gets initialized, but can only be created
    * later. It is then stored in an atomic reference, so that it can be
    * accessed from arbitrary threads.
    */
  private val refOutputActor = new AtomicReference[ActorRef[OutputCommand]]

  /**
    * Creates a [[LoggerContext]] for this shell application. This function
    * sets up the initial context and adds the custom appender to propagate all
    * log output to the output actor. This function must be called at the very
    * beginning of the application, before the creation of the actor system
    * (otherwise, the actor system will not use the desired logging
    * configuration). Unfortunately, at this time, the custom appender cannot
    * be fully initialized, since no output actor exists yet.
    *
    * @return the pre-initialized [[LoggerContext]]
    */
  def initializeLogging(): LoggerContext =
    val configBuilder = ConfigurationBuilderFactory.newConfigurationBuilder()
    val configuration = configBuilder.add(
      configBuilder
        .newRootLogger(Level.DEBUG)
    ).build(false)

    val context = Configurator.initialize(configuration)

    val appender = createOutputAppender(context)
    appender.start()
    configuration.addAppender(appender)
    configuration.getRootLogger.addAppender(appender, Level.DEBUG, null)
    context.updateLoggers()
    context

  /**
    * Initializes the output system based on the given parameters. This 
    * function must be called before producing any output in the main command
    * loop making use of the ''output()'' function.
    *
    * @param system the actor system
    * @param writer the writer for writing to the console
    */
  def initializeOutput(system: classic.ActorSystem, writer: PrintAboveWriter): Unit =
    val outputActor = system.spawn(handleOutputCommand(writer), "outputActor")
    refOutputActor.set(outputActor)

  /**
    * Writes the given lines of text (generated by a command) to the console.
    *
    * @param lines the lines of text to output
    */
  def output(lines: List[String]): Unit =
    sendOutputCommand(OutputCommand.OutputText(lines))

  /**
    * Shuts down the output handling done by this module. This function should
    * be called when the application ends. Afterward, no output is possible via
    * the functions defined here.
    */
  def shutdownOutput(): Unit =
    if sendOutputCommand(OutputCommand.Stop) then
      refOutputActor.set(null)

  /**
    * The main command handler function of the output actor.
    *
    * @param writer the writer to print to the console
    * @return the behavior of the actor
    */
  private def handleOutputCommand(writer: PrintAboveWriter): Behavior[OutputCommand] =
    Behaviors.receiveMessage:
      case OutputCommand.OutputLog(message) =>
        writer.write(message)
        writer.flush()
        Behaviors.same
      case OutputCommand.OutputText(lines) =>
        lines.foreach(line => writer.write(line + '\n'))
        writer.flush()
        Behaviors.same
      case OutputCommand.Stop =>
        Behaviors.stopped

  /**
    * Creates a special custom [[Appender]] that forwards log events to the
    * output actor if it is available. If the actor has not yet been created,
    * the log message is written to the console.
    *
    * @param context the [[LoggerContext]]
    * @return the output appender
    */
  private def createOutputAppender(context: LoggerContext): Appender =
    new AbstractAppender(AppenderName, null, createLayout(context), false, Array.empty):
      override def append(event: LogEvent): Unit =
        val message = formatEvent(event, getLayout)
        if !sendOutputCommand(OutputCommand.OutputLog(message)) then
          println(message)

  /**
    * Creates a [[PatternLayout]] object with the default pattern used by this
    * application.
    *
    * @param context the logger context
    * @return the pattern layout
    */
  private def createLayout(context: LoggerContext): PatternLayout =
    PatternLayout.newBuilder()
      .withConfiguration(context.getConfiguration)
      .withPattern("%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n")
      .withCharset(StandardCharsets.UTF_8)
      .build()

  /**
    * Formats a [[LogEvent]] using a [[Layout]].
    *
    * @param event  the event
    * @param layout the layout
    * @return the resulting string for the event
    */
  private def formatEvent(event: LogEvent, layout: Layout[?]): String =
    val bytes = layout.toByteArray(event)
    val charSet = layout match
      case s: StringLayout => s.getCharset
      case _ => StandardCharsets.UTF_8

    new String(bytes, 0, bytes.length, charSet)

  /**
    * Sends the given command to the output actor if it is available. The
    * return value indicates whether this was successful.
    *
    * @param command the command to send
    * @return a flag whether the command could be sent
    */
  private def sendOutputCommand(command: => OutputCommand): Boolean =
    val actor = refOutputActor.get()
    if actor != null then
      actor ! command
      true
    else
      false
